# Generated by Django 5.1.3 on 2024-11-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_adminuser_delete_admin_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='img',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
