# Generated by Django 5.1.3 on 2024-11-09 15:59

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', colorfield.fields.ColorField(default='#0000', image_field=None, max_length=25, samples=None)),
                ('book', models.ManyToManyField(related_name='booktags', to='apis.book')),
            ],
        ),
    ]
