# Generated by Django 5.1.3 on 2024-11-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_remove_booktag_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookTag',
        ),
    ]
