# Generated by Django 5.1.3 on 2024-11-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_delete_booktag'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bookdetail',
            name='book',
        ),
        migrations.RemoveField(
            model_name='img',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='book_detail',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='borrow_record',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.DeleteModel(
            name='BookDetail',
        ),
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
