# Generated by Django 5.1.3 on 2024-11-22 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_author_category_rename_user_login_book_bookdetail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdetail',
            old_name='is_available',
            new_name='is_active',
        ),
    ]
